### ISSUE TITLE
Deploy of Server on Heroku

### ISSUE THREAD

**Issue by lhcavalcanti** [RC-Dynamics/presence-server#1]
The server connects and works properly on computer, but when deployed to Heroku, this doesn't runs.

**Comment by bebetocf** [comment]
Need it to add the mLab's add-on the Heroku. Also need get the MongoDB URL (commit: https://github.com/RC-Dynamics/presence-server/commit/26044c658a4b845e25911f3aa669bd2cdbeac29f) and the express port from environment variables(commit: https://github.com/RC-Dynamics/presence-server/commit/f31308691bad5c63628215fbc290cdb02f448c87).
